apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
  serviceName: "mongodb-headless-svc" # this should be headless service
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop"
      resources:
        requests:
          storage: 2Gi