apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: database
  serviceName: "rabbitmq-headless-svc" # this should be headless service
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}"
        envFrom:
        - secretRef:
            name: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop"
      resources:
        requests:
          storage: 2Gi